services:
  - type: web
    name: vercelgen
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 --chdir api index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
